// Schema of supabase public.tickets table
export type Ticket = {
  ticket_id: string;
  ticket_reference_id: string;
  department?: string | null;
  department_id?: string | null;
  contact_name?: string | null;
  contact_id?: string | null;
  email?: string | null;
  phone?: string | null;
  subject?: string | null;
  description?: string | null;
  status?: string | null;
  product_name?: string | null;
  product_id?: string | null;
  ticket_owner?: string | null;
  ticket_owner_id?: string | null;
  created_by?: string | null;
  created_by_id?: number | null;
  modified_by?: string | null;
  modified_by_id?: string | null;
  created_time?: Date | null;
  modified_time?: Date | null;
  resolution?: string | null;
  to_address?: string | null;
  account_name?: string | null;
  account_id?: string | null;
  due_date?: string | null;
  priority?: string | null;
  mode?: string | null;
  category?: string | null;
  sub_category?: string | null;
  ticket_closed_time?: string | null;
  is_overdue?: boolean | null;
  is_escalated?: boolean | null;
  classification?: string | null;
  time_to_respond?: string | null;
  team?: string | null;
  team_id?: string | null;
  tags?: string | null;
  ticket_on_hold_time?: string | null;
  language?: string | null;
  child_ticket_count?: string | null;
  response_due_date?: string | null;
  is_response_overdue?: boolean | null;
};