export interface ThreadPayload {
  id: string | null;
  ticketId: string | null;
  content: string | null;
  author?: {
    id: string | null;
    name?: string | null;
    type?: string | null;
    photoURL?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
  } | null;
  createdTime: string | null;
  channel?: string | null;
  direction: 'in' | 'out' | null;
  attachments?: any[] | null;
  isDescriptionThread?: boolean | null;
  canReply?: boolean | null;
  isContentTruncated?: boolean | null;
  bcc?: string[] | null;
  departmentId?: string | null;
  source?: any | null;
  contentType?: string | null;
  summary?: string | null;
  cc?: string[] | null;
  visibility?: string | null;
  fullContentURL?: string | null;
  isForward?: boolean | null;
  hasAttach?: boolean | null;
  responderId?: string | null;
  replyTo?: string | null;
  attachmentCount?: number | null;
  to?: string[] | null;
  fromEmailAddress?: string | null;
  status?: string | null;
}

export interface TicketPayload {
  id: string | null;
  ticketNumber: string | null;
  modifiedTime?: string | null;
  subCategory?: string | null;
  statusType?: string | null;
  subject?: string | null;
  departmentId?: string | null;
  dueDate?: string | null;
  channel?: string | null;
  onholdTime?: string | null;
  language?: string | null;
  source?: {
    appName?: string | null;
    extId?: string | null;
    permalink?: string | null;
    type?: string | null;
    appPhotoURL?: string | null;
  } | null;
  resolution?: string | null;
  sharedDepartments?: any[];
  closedTime?: string | null;
  approvalCount?: string | null;
  isOverDue?: boolean | null;
  isTrashed?: boolean | null;
  contact?: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    mobile?: string | null;
    id?: string | null;
    isSpam?: boolean | null;
    type?: string | null;
    email?: string | null;
    account?: any | null;
  } | null;
  createdTime?: string | null;
  isResponseOverdue?: boolean | null;
  firstThread?: any | null;
  customerResponseTime?: string | null;
  productId?: string | null;
  contactId?: string | null;
  threadCount?: string | null;
  secondaryContacts?: any[];
  priority?: string | null;
  classification?: string | null;
  commentCount?: string | null;
  accountId?: string | null;
  taskCount?: string | null;
  phone?: string | null;
  webUrl?: string | null;
  isSpam?: boolean | null;
  assignee?: {
    photoURL?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    id?: string | null;
    email?: string | null;
  } | null;
  lastActivityTime?: string | null;
  status?: string | null;
  entitySkills?: any[];
  sentiment?: string | null;
  customFields?: {
    severityPercentage?: string | null;
    dateofPurchase?: string | null;
    url?: string | null;
  } | null;
  isArchived?: boolean | null;
  description?: string | null;
  timeEntryCount?: string | null;
  channelRelatedInfo?: any | null;
  responseDueDate?: string | null;
  isDeleted?: boolean | null;
  modifiedBy?: string | null;
  followerCount?: string | null;
  email?: string | null;
  layoutDetails?: {
    id?: string | null;
    layoutName?: string | null;
  } | null;
  channelCode?: string | null;
  cf?: {
    cf_url?: string | null;
    cf_severityPercentage?: string | null;
    cf_dateofPurchase?: string | null;
  } | null;
  isFollowing?: boolean | null;
  assigneeId?: string | null;
  layoutId?: string | null;
  createdBy?: string | null;
  teamId?: string | null;
  tagCount?: string | null;
  isEscalated?: boolean | null;
  attachmentCount?: string | null;
  category?: string | null;
  descAttachments?: Array<{
    size?: string | null;
    name?: string | null;
    href?: string | null;
    id?: string | null;
  }>;
}